### ISSUE TITLE
gdb-variables window cannot open correctly

### ISSUE THREAD

**Issue by adiaa** [cpiger/vimgdb-for-vim7.3#2]
I have complied your patch and installed the vimGdb_runtime just follow your guidance. The problem is it just splite a window that names /current/path/gdb-variables when i type :bel 30vsplit gdb-variables in vim. After that, if i select a variable , then type C-p, it will show viariable value in current window (code window), but gdb-variables window.
Screenshot of two gdb-variables window is below
![2015-05-26-130529_1365x690_scrot](https://cloud.githubusercontent.com/assets/11069967/7805679/47b62ef4-03a9-11e5-9b43-13c3e807078c.png)
Actually, it has works very well when i first install it for a moment. But the problem just pop up after i modified the macros/gdb_mappings.vim(only remember is i modified the gdb_mappipngs.vim, a little key remap). I'm not sure whether is that cuase this problem. The gdb-variables window has work once i reinstall vim_7.3 whith patch and vimGdb_runtime, but it down again just a little moment. It cannot work even i try to retreat all modifies. I also have tried to reinstall both vim7.3 and vim7.4 with your patch as well as vimGdb_runtime for many times, its just not work now.
The environment of my computer is Debian_7.8_64bit, vim_7.3, gdb_7.4.1, gcc_4.7.2.
I have google it, seems  no one have this problem. So maybe i have done something bad, but i donot remember what i have done! I love this plugin, if you know how to fix it, please please tell me!

**Comment by cpiger** [comment]
please don't use "bel 30vsplit gdb-variables", 
try "bel 30vsplit gdbvars"

**Comment by cpiger** [comment]
and "set gdbvar=gdbvars" in your .vimrc
